import './index.scss'
import {Noto_Sans} from 'next/font/google'
import React from "react";

const notoSans = Noto_Sans({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="ru">
    <body suppressHydrationWarning={true} className={notoSans.className}>{children}</body>
    </html>
  )
}
