"use client";
import Htag from "@/components/Htag/Htag";
import Button from "@/components/Button/Button";
import P from "@/components/P/P";
import Tag from "@/components/Tag/Tag";
import Rating from "@/components/Rating/Rating";
import {useState} from "react";
import {withLayout} from "@/layout/Layout";

export const metadata = {
  title: 'Create Next',
  description: 'Generated by create next app',
}

function Home() {

  const [rating, setRating] = useState<number>(4);

  return (
    <>
      <Htag tag='h1'>Текст</Htag>
      <Button arrow='right'> Button</Button>
      <Button arrow='right' appearance='ghost'>Button</Button>
      <P size='l'>Большой</P>
      <P>Средний</P>
      <P size='s'>Маленький</P>
      <Tag size='s'>Маленький</Tag>
      <Tag size='m'>Middle</Tag>
      <Tag size='m' color='green'>green</Tag>
      <Tag size='m' color='red'>red</Tag>
      <Tag size='m' color='primary'>primary</Tag>

      <Rating rating={rating} setRating={setRating} isEditable/>
    </>
  )
}

export default withLayout(Home)